<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Manager.aspx.cs" Inherits="Manager" EnableEventValidation="false" ValidateRequest="false"  MasterPageFile="~/MasterPage.master" %>

   <asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
        
    <div class="auto-style1">
    
        <div class="auto-style4">
    
        <asp:Label ID="AdminLabel" runat="server" Text="Welcome ......."></asp:Label>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <asp:Button ID="AdminLogoutButton" runat="server" OnClick="AdminLogoutButton_Click" Text="Log Out" />
    
            &nbsp;&nbsp;
    
            <br />
            <br />
            <span class="auto-style2"><strong><br />
            </strong>
            <table class="auto-style5">
                <tr>
                    <td class="auto-style7"><span class="auto-style2"><strong>&nbsp;</strong></span></td>
                    <td class="auto-style8">
                        </td>
                    <td class="auto-style8">
                        </td>
                    <td class="auto-style11">
                        </td>
                </tr>
                <tr>
                    <td class="auto-style11" colspan="4"></td>
                </tr>
                <tr>
                    <td class="auto-style6" colspan="4">
                        <!-- DropDown box for chose action -->
                        <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
                            <asp:ListItem Value="0">User Database</asp:ListItem>
                            <asp:ListItem Value="1">Tour Package Database</asp:ListItem>
                            <asp:ListItem Value="2">Booking Information</asp:ListItem>
                            <asp:ListItem Value="3">Managing Admin Database</asp:ListItem>
                            <asp:ListItem Value="4">Contact Messages</asp:ListItem>
                        </asp:DropDownList>
                    </td>
                </tr>
            </table>
            <br />
            <br />
            <br />
            </span>
        </div>
        <!-- Using multiview option for view in same screen -->
        <asp:MultiView ID="MultiView1" runat="server">

            <asp:View ID="View1" runat="server">
        <div class="auto-style3">
            <span class="auto-style2"><strong>
            <br />
            Managing User Database:</strong></span><br />
        </div>
    <!-- User Database connection -->
        <asp:SqlDataSource ID="SqlDataSourceRegistration" runat="server" ConnectionString="<%$ ConnectionStrings:RegistrationConnectionString %>" SelectCommand="SELECT * FROM [Userdata]" UpdateCommand="UPDATE [Userdata] Set [User_Name]=@User_Name, [Email]=@Email, [Password]=@Password, [Address]=@Address, [Utype]=@Utype Where [ID]=@ID" DeleteCommand="DELETE [Userdata] Where [ID]=@id"></asp:SqlDataSource>
       <!-- User Table show -->
                 <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" BackColor="#DEBA84" BorderColor="#DEBA84" BorderStyle="None" BorderWidth="1px" CellPadding="3" CellSpacing="2" DataKeyNames="ID" DataSourceID="SqlDataSourceRegistration" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" AllowPaging="True" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" Width="881px">
            <Columns>
                <asp:BoundField DataField="ID" HeaderText="ID" ReadOnly="True" SortExpression="ID" InsertVisible="False" />
                <asp:BoundField DataField="User_Name" HeaderText="User_Name" SortExpression="User_Name" />
                <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                <asp:BoundField DataField="Utype" HeaderText="Utype" SortExpression="Utype" />
                <asp:BoundField DataField="Full_Name" HeaderText="Full_Name" SortExpression="Full_Name" />
                <asp:BoundField DataField="Mobile" HeaderText="Mobile" SortExpression="Mobile" />
            </Columns>
            <FooterStyle BackColor="#F7DFB5" ForeColor="#8C4510" />
            <HeaderStyle BackColor="#A55129" Font-Bold="True" ForeColor="White" />
            <PagerStyle ForeColor="#8C4510" HorizontalAlign="Center" />
            <RowStyle BackColor="#FFF7E7" ForeColor="#8C4510" />
            <SelectedRowStyle BackColor="#738A9C" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#FFF1D4" />
            <SortedAscendingHeaderStyle BackColor="#B95C30" />
            <SortedDescendingCellStyle BackColor="#F1E5CE" />
            <SortedDescendingHeaderStyle BackColor="#93451F" />
        </asp:GridView>

            </asp:View>
            <asp:View ID="View2" runat="server">
        <div class="auto-style3">
            <br />
            <span class="auto-style2"><strong>
            <br />
            Managing Tour Package Database:<br />
            <br />
            <div class="auto-style3">
            <span class="auto-style2"><strong>
                <!-- Package Database Entry form -->
                <asp:FormView ID="FormView1" runat="server" AllowPaging="True" DataKeyNames="Package_Id" DataSourceID="SqlDataSourcePackage" DefaultMode="Insert" Height="203px" Width="301px" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Both" CssClass="auto-style16" OnPageIndexChanging="FormView1_PageIndexChanging">
                    <EditItemTemplate>
                        Package_Id:
                        <asp:Label ID="Package_IdLabel1" runat="server" Text='<%# Eval("Package_Id") %>' />
                        <br />
                        Package_Name:
                        <asp:TextBox ID="Package_NameTextBox" runat="server" Text='<%# Bind("Package_Name") %>' />
                        <br />
                        Price:
                        <asp:TextBox ID="PriceTextBox" runat="server" Text='<%# Bind("Price") %>' />
                        <br />
                        Package_Pic:
                        <asp:TextBox ID="Package_PicTextBox" runat="server" Text='<%# Bind("Package_Pic") %>' />
                        <br />
                        Discription:
                        <asp:TextBox ID="DiscriptionTextBox" runat="server" Text='<%# Bind("Discription") %>' />
                        <br />
                        <asp:LinkButton ID="UpdateButton" runat="server" CausesValidation="True" CommandName="Update" Text="Update" />
                        &nbsp;<asp:LinkButton ID="UpdateCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" />
                    </EditItemTemplate>
                    <EditRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                    <FooterStyle BackColor="White" ForeColor="#000066" />
                    <HeaderStyle BackColor="#006699" Font-Bold="True" ForeColor="White" />
                    <InsertItemTemplate>
                        Package_Id:
                        <asp:TextBox ID="Package_IdTextBox" runat="server" Text='<%# Bind("Package_Id") %>' />
                        <br />
                        Package_Name:
                        <asp:TextBox ID="Package_NameTextBox" runat="server" Text='<%# Bind("Package_Name") %>' />
                        <br />
                        Price:
                        <asp:TextBox ID="PriceTextBox" runat="server" Text='<%# Bind("Price") %>' />
                        <br />
                        Package_Pic:
                        <asp:TextBox ID="Package_PicTextBox" runat="server" Text='<%# Bind("Package_Pic") %>' />
                        <br />
                        Discription:
                        <asp:TextBox ID="DiscriptionTextBox" runat="server" Text='<%# Bind("Discription") %>' />
                        <br />
                        <asp:LinkButton ID="InsertButton" runat="server" CausesValidation="True" CommandName="Insert" Text="Insert" />
                        &nbsp;<asp:LinkButton ID="InsertCancelButton" runat="server" CausesValidation="False" CommandName="Cancel" Text="Cancel" />
                    </InsertItemTemplate>
                    <ItemTemplate>
                        Package_Id:
                        <asp:Label ID="Package_IdLabel" runat="server" Text='<%# Eval("Package_Id") %>' />
                        <br />
                        Package_Name:
                        <asp:Label ID="Package_NameLabel" runat="server" Text='<%# Bind("Package_Name") %>' />
                        <br />
                        Price:
                        <asp:Label ID="PriceLabel" runat="server" Text='<%# Bind("Price") %>' />
                        <br />
                        Package_Pic:
                        <asp:Label ID="Package_PicLabel" runat="server" Text='<%# Bind("Package_Pic") %>' />
                        <br />
                        Discription:
                        <asp:Label ID="DiscriptionLabel" runat="server" Text='<%# Bind("Discription") %>' />
                        <br />
                        <asp:LinkButton ID="EditButton" runat="server" CausesValidation="False" CommandName="Edit" Text="Edit" />
                        &nbsp;<asp:LinkButton ID="DeleteButton" runat="server" CausesValidation="False" CommandName="Delete" Text="Delete" />
                        &nbsp;<asp:LinkButton ID="NewButton" runat="server" CausesValidation="False" CommandName="New" Text="New" />
                    </ItemTemplate>
                    <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                    <RowStyle ForeColor="#000066" />
                </asp:FormView>
                </strong></span>
            </div>
            <br />
            <br />
            <br />
            </strong></span><br />
        </div>
                <!-- package Database connection -->
        <asp:SqlDataSource ID="SqlDataSourcePackage" runat="server" ConnectionString="<%$ ConnectionStrings:RegistrationConnectionString %>" SelectCommand="SELECT * FROM [Package]"  UpdateCommand="UPDATE [Package] Set [Package_Name]=@Package_Name, [Price]=@Price, [Package_Pic]=@Package_Pic, [Discription]=@Discription Where [Package_Id]=@Package_Id" DeleteCommand="DELETE [Package] Where [Package_Id]=@Package_id" InsertCommand="INSERT INTO Package(Package_Id, Package_Name, Price, Package_Pic, Discription) VALUES (@Package_Id, @Package_Name, @Price, @Package_Pic, @Discription)" OnSelecting="SqlDataSourcePackage_Selecting">
            <DeleteParameters>
                <asp:Parameter Name="Package_id" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="Package_Id" />
                <asp:Parameter Name="Package_Name" />
                <asp:Parameter Name="Price" />
                <asp:Parameter Name="Package_Pic" />
                <asp:Parameter Name="Discription" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="Package_Name" />
                <asp:Parameter Name="Price" />
                <asp:Parameter Name="Package_Pic" />
                <asp:Parameter Name="Discription" />
                <asp:Parameter Name="Package_Id" />
            </UpdateParameters>
                </asp:SqlDataSource>
        <br />
                <!-- showing Package Database -->
        <asp:GridView ID="GridView2" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" DataKeyNames="Package_Id" DataSourceID="SqlDataSourcePackage" ForeColor="Black" Width="880px" AllowCustomPaging="True" Height="1000px">
            <Columns>
                <asp:BoundField DataField="Package_Id" HeaderText="Package_Id" ReadOnly="True" SortExpression="Package_Id" />
                <asp:BoundField DataField="Package_Name" HeaderText="Package_Name" SortExpression="Package_Name" />
                <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
                <asp:BoundField DataField="Package_Pic" HeaderText="Package_Pic" SortExpression="Package_Pic" />
                <asp:BoundField DataField="Discription" HeaderText="Discription" SortExpression="Discription" />
            </Columns>
            <FooterStyle BackColor="#CCCCCC" />
            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
            <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
            <RowStyle BackColor="White" />
            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
            <SortedAscendingCellStyle BackColor="#F1F1F1" />
            <SortedAscendingHeaderStyle BackColor="Gray" />
            <SortedDescendingCellStyle BackColor="#CAC9C9" />
            <SortedDescendingHeaderStyle BackColor="#383838" />
        </asp:GridView>
            </asp:View>
            <asp:View ID="View3" runat="server">
        <div class="auto-style3">
            <br />
            <br />
            <span class="auto-style2"><strong>Managing Booking:<br /> &nbsp;&nbsp; </strong>
            <asp:Button ID="Button1" runat="server" OnClick="Button1_Click" Text="Booking Report" />
            &nbsp;&nbsp;&nbsp;&nbsp;<asp:Label ID="LabelConfig" runat="server"></asp:Label>
            <br />
            &nbsp;&nbsp;&nbsp; </span>
            <asp:Button ID="Button2" runat="server" OnClick="Button2_Click" style="height: 26px" Text="Button" />
            <span class="auto-style2">
            <asp:Label ID="LabelConfig0" runat="server"></asp:Label>
            <br />
                <!-- show Booking Database -->
            <asp:SqlDataSource ID="SqlDataSourceConfiguration" runat="server" ConnectionString="<%$ ConnectionStrings:RegistrationConnectionString %>" SelectCommand="SELECT * FROM [Messages]"></asp:SqlDataSource>
            </span>
            <br />
            <br />
            <br />
            <asp:SqlDataSource ID="SqlDataSourceBooking" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:RegistrationConnectionString %>" DeleteCommand="DELETE FROM [Booking] WHERE [ID] = @original_ID AND [Booking_Date] = @original_Booking_Date AND [User_Name] = @original_User_Name AND [Mobile] = @original_Mobile AND [Address] = @original_Address AND [Package_Id] = @original_Package_Id AND [Package_Name] = @original_Package_Name AND [Price] = @original_Price AND [Quantity] = @original_Quantity AND [Total_Price] = @original_Total_Price" InsertCommand="INSERT INTO [Booking] ([Booking_Date], [User_Name], [Mobile], [Address], [Package_Id], [Package_Name], [Price], [Quantity], [Total_Price]) VALUES (@Booking_Date, @User_Name, @Mobile, @Address, @Package_Id, @Package_Name, @Price, @Quantity, @Total_Price)" OldValuesParameterFormatString="original_{0}" SelectCommand="SELECT * FROM [Booking]" UpdateCommand="UPDATE [Booking] SET [Booking_Date] = @Booking_Date, [User_Name] = @User_Name, [Mobile] = @Mobile, [Address] = @Address, [Package_Id] = @Package_Id, [Package_Name] = @Package_Name, [Price] = @Price, [Quantity] = @Quantity, [Total_Price] = @Total_Price WHERE [ID] = @original_ID AND [Booking_Date] = @original_Booking_Date AND [User_Name] = @original_User_Name AND [Mobile] = @original_Mobile AND [Address] = @original_Address AND [Package_Id] = @original_Package_Id AND [Package_Name] = @original_Package_Name AND [Price] = @original_Price AND [Quantity] = @original_Quantity AND [Total_Price] = @original_Total_Price">
                <DeleteParameters>
                    <asp:Parameter Name="original_ID" Type="Int32" />
                    <asp:Parameter Name="original_Booking_Date" Type="DateTime" />
                    <asp:Parameter Name="original_User_Name" Type="String" />
                    <asp:Parameter Name="original_Mobile" Type="String" />
                    <asp:Parameter Name="original_Address" Type="String" />
                    <asp:Parameter Name="original_Package_Id" Type="Int32" />
                    <asp:Parameter Name="original_Package_Name" Type="String" />
                    <asp:Parameter Name="original_Price" Type="Int32" />
                    <asp:Parameter Name="original_Quantity" Type="Int32" />
                    <asp:Parameter Name="original_Total_Price" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Booking_Date" Type="DateTime" />
                    <asp:Parameter Name="User_Name" Type="String" />
                    <asp:Parameter Name="Mobile" Type="String" />
                    <asp:Parameter Name="Address" Type="String" />
                    <asp:Parameter Name="Package_Id" Type="Int32" />
                    <asp:Parameter Name="Package_Name" Type="String" />
                    <asp:Parameter Name="Price" Type="Int32" />
                    <asp:Parameter Name="Quantity" Type="Int32" />
                    <asp:Parameter Name="Total_Price" Type="Int32" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Booking_Date" Type="DateTime" />
                    <asp:Parameter Name="User_Name" Type="String" />
                    <asp:Parameter Name="Mobile" Type="String" />
                    <asp:Parameter Name="Address" Type="String" />
                    <asp:Parameter Name="Package_Id" Type="Int32" />
                    <asp:Parameter Name="Package_Name" Type="String" />
                    <asp:Parameter Name="Price" Type="Int32" />
                    <asp:Parameter Name="Quantity" Type="Int32" />
                    <asp:Parameter Name="Total_Price" Type="Int32" />
                    <asp:Parameter Name="original_ID" Type="Int32" />
                    <asp:Parameter Name="original_Booking_Date" Type="DateTime" />
                    <asp:Parameter Name="original_User_Name" Type="String" />
                    <asp:Parameter Name="original_Mobile" Type="String" />
                    <asp:Parameter Name="original_Address" Type="String" />
                    <asp:Parameter Name="original_Package_Id" Type="Int32" />
                    <asp:Parameter Name="original_Package_Name" Type="String" />
                    <asp:Parameter Name="original_Price" Type="Int32" />
                    <asp:Parameter Name="original_Quantity" Type="Int32" />
                    <asp:Parameter Name="original_Total_Price" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <!-- Show Booking Data -->
            <asp:GridView ID="GridView6" runat="server" AllowPaging="True" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="ID" DataSourceID="SqlDataSourceBooking" ForeColor="#333333" GridLines="None">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" />
                    <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                    <asp:BoundField DataField="Booking_Date" HeaderText="Booking_Date" SortExpression="Booking_Date" />
                    <asp:BoundField DataField="User_Name" HeaderText="User_Name" SortExpression="User_Name" />
                    <asp:BoundField DataField="Mobile" HeaderText="Mobile" SortExpression="Mobile" />
                    <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                    <asp:BoundField DataField="Package_Id" HeaderText="Package_Id" SortExpression="Package_Id" />
                    <asp:BoundField DataField="Package_Name" HeaderText="Package_Name" SortExpression="Package_Name" />
                    <asp:BoundField DataField="Price" HeaderText="Price" SortExpression="Price" />
                    <asp:BoundField DataField="Quantity" HeaderText="Quantity" SortExpression="Quantity" />
                    <asp:BoundField DataField="Total_Price" HeaderText="Total_Price" SortExpression="Total_Price" />
                </Columns>
                <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                <SortedAscendingCellStyle BackColor="#FDF5AC" />
                <SortedAscendingHeaderStyle BackColor="#4D0000" />
                <SortedDescendingCellStyle BackColor="#FCF6C0" />
                <SortedDescendingHeaderStyle BackColor="#820000" />
            </asp:GridView>
            <br />
            <br />
        </div>
            </asp:View>

            <asp:View ID="View4" runat="server">
        <div class="auto-style3">
            <br />
            <br />
              <!-- Admin Database connection --> <!-- Manage Admin Database -->
            <span class="auto-style2"><strong>Managing Admin Database:</strong></span><br />
          
            <asp:SqlDataSource ID="SqlDataSourceAdmin" runat="server" ConnectionString="<%$ ConnectionStrings:RegistrationConnectionString %>" DeleteCommand="DELETE FROM [Admindata] WHERE [ID] = @ID" InsertCommand="INSERT INTO [Admindata] ([User_Name], [Email], [Password], [Address]) VALUES (@User_Name, @Email, @Password, @Address)" SelectCommand="SELECT * FROM [Admindata]" UpdateCommand="UPDATE [Admindata] SET [User_Name] = @User_Name, [Email] = @Email, [Password] = @Password, [Address] = @Address WHERE [ID] = @ID">
               
                 <DeleteParameters>
                    <asp:Parameter Name="ID" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="User_Name" Type="String" />
                    <asp:Parameter Name="Email" Type="String" />
                    <asp:Parameter Name="Password" Type="Int32" />
                    <asp:Parameter Name="Address" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="User_Name" Type="String" />
                    <asp:Parameter Name="Email" Type="String" />
                    <asp:Parameter Name="Password" Type="Int32" />
                    <asp:Parameter Name="Address" Type="String" />
                    <asp:Parameter Name="ID" Type="Int32" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <br />
            <asp:GridView ID="GridView4" runat="server" AllowPaging="True" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="ID" DataSourceID="SqlDataSourceAdmin" ForeColor="#333333" GridLines="None" Width="866px">
                <AlternatingRowStyle BackColor="White" />
                <Columns>
                    <asp:CommandField ShowDeleteButton="True" ShowEditButton="True" />
                    <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                    <asp:BoundField DataField="User_Name" HeaderText="User_Name" SortExpression="User_Name" />
                    <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                    <asp:BoundField DataField="Password" HeaderText="Password" SortExpression="Password" />
                    <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                </Columns>
                <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                <SortedAscendingCellStyle BackColor="#FDF5AC" />
                <SortedAscendingHeaderStyle BackColor="#4D0000" />
                <SortedDescendingCellStyle BackColor="#FCF6C0" />
                <SortedDescendingHeaderStyle BackColor="#820000" />
            </asp:GridView>
            <br />
            <br />
        </div>

            </asp:View>
            <asp:View ID="View5" runat="server">
                <div class="auto-style20">
                    <strong>Contact Messages<br /> </strong>
                </div>
                <!-- show contact data -->
                <asp:GridView ID="GridView5" runat="server" AllowPaging="True" AutoGenerateColumns="False" CellPadding="4" DataKeyNames="ID" DataSourceID="SqlDataSourceConfiguration" ForeColor="#333333" GridLines="None">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:BoundField DataField="ID" HeaderText="ID" InsertVisible="False" ReadOnly="True" SortExpression="ID" />
                        <asp:BoundField DataField="User_Name" HeaderText="User_Name" SortExpression="User_Name" />
                        <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
                        <asp:BoundField DataField="Mobile" HeaderText="Mobile" SortExpression="Mobile" />
                        <asp:BoundField DataField="Messages" HeaderText="Messages" SortExpression="Messages" />
                    </Columns>
                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
                <br />
<br />
                  

            </asp:View>
        </asp:MultiView>

        <br />
        <br />
    </div>
       </asp:Content>
<asp:Content ID="Content2" runat="server" contentplaceholderid="head">
    <style type="text/css">
        .auto-style1 {
            width: 843px;
            height: 174px;
        }
        .auto-style2 {
            text-align: right;
        }
        .auto-style3 {
            text-align: left;
        }
        .auto-style4 {
            text-align: left;
            width: 479px;
        }
        .auto-style5 {
            text-align: left;
            width: 466px;
        }
        .auto-style6 {
            text-align: left;
            width: 458px;
        }
        .auto-style7 {
            text-align: left;
            width: 451px;
            height: 23px;
        }
        .auto-style8 {
            text-align: left;
            width: 446px;
            height: 23px;
        }
        .auto-style11 {
            text-align: left;
            width: 458px;
            height: 23px;
        }
        .auto-style12 {
            text-align: right;
            width: 127px;
        }
        .auto-style13 {
            text-align: right;
            width: 127px;
            height: 34px;
        }
        .auto-style14 {
            text-align: left;
            width: 276px;
            height: 34px;
        }
        .auto-style15 {
            text-align: left;
            width: 276px;
        }
        .auto-style16 {
            margin-left: 237px;
        }
        .auto-style19 {
            width: 839px;
        }
        .auto-style20 {
            text-align: center;
        }
    </style>
</asp:Content>
